server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
      name:  demo
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/..
    username: ENC(root)
    password:
  jpg:
    hibernate.ddl-auto: none
    show-sql: show-sql
    properties:
        hibernate:
            format_sql : true
  data:
    redis:
      host: localhost
      port: 6379

plitche:
    hub:
      short:
        url:
          id: YRhZcJKcaB1VTGI1vHik
          secreate: OpiPdIeaUM
      portal: naver

jasypt: # 프로퍼티 암호화 설정
    encryptor:
      bean: jasyptStringEncryptor

---
spring:
  config:
    activate:
      on-profile: local
plitche:
  hub:
    loading:
      message: "## local 환경으로 실행되었습니다 ##"


---
spring:
  config:
    activate:
      on-profile: dev
plitche:
  hub:
    loading:
      message: "## dev 환경으로 실행되었습니다 ##"

---
spring:
  config:
    activate:
      on-profile: prod
plitche:
  hub:
    loading:
      message: "## production 환경으로 실행되었습니다 ##"
